###
POST http://localhost:8080/level/create
Content-Type: application/json

{
  "id": "level01",
  "map": {
    "id": 5
  },
  "player": {
    "id": 1
  },
  "npcs": [
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    },
    {
      "id": 4
    }
  ],
  "bonuses": [
    {
      "id": 1,
      "bonus": {
        "id": 1
      }
    },
    {
      "id": 2,
      "bonus": {
        "id": 2
      }
    },
    {
      "id": 3,
      "bonus": {
        "id": 3
      }
    },
    {
      "id": 4,
      "bonus": {
        "id": 4
      }
    }
  ]
}

###
GET localhost:8080/level/getAll

###
POST localhost:8080/level/get
Content-Type: text/plain

level01