###
POST http://localhost:8080/map/create
Content-Type: application/json

{
  "sizeX": 25,
  "sizeY": 20
}

###
GET localhost:8080/map/getAll

###
POST localhost:8080/map/get
Content-Type: text/plain

1